version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: '10:00'
  commit-message:
    prefix: "chore(bot):"
  groups:
    elixir:
      patterns: ["*"]
      update-types: ["minor", "patch"]
